cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: AKIA4MFLODBGAT3YKLGX
      secret-key: 
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/850763061324/queue-Sanjay
server:
  port: 8088
    
